### PR TITLE
DX-417: update from dbt_utils upstream

### PR DESCRIPTION
**Pull request by elliottohara**

### CODE REVIEW

**Review by awshepard — APPROVED** [review]
nit this was actually DX-415, not 417, :).

i assume there's not much to do here besides stamp it since it's coming from upstream.  we should be able to run a test locally by setting the revision to this commit in packages.yml, right?

**Comment by awshepard** [comment]
ah, so, i found out putting the specific commit sha into the revision: in packages.yml doesn't work, i get an unknown pathspec, but i _can_ put DX-417 and it'll actually resolve the branch name. so that's cool.

but also, this version of dbt_utils now requires dbt >=0.18.0 ... can of worms, here we come :)

**Comment by elliottohara** [comment]
> ah, so, i found out putting the specific commit sha into the revision: in packages.yml doesn't work, i get an unknown pathspec, but i _can_ put DX-417 and it'll actually resolve the branch name. so that's cool.
> 
> but also, this version of dbt_utils now requires dbt >=0.18.0, so uh ... let's not merge this yet ... can of worms, here we come :)

Yep, I found that out last time I tried to version it, that's why I started using the the `GU` tags...

**Comment by elliottohara** [comment]
Gunna go ahead and merge so I can tag it off master. Worst case, we just use the last tag.

**Pull request merged**
